version: '3'
services:
  storeapp:
    container_name: storeapp
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    depends_on:
      - stores-postgres
    networks:
      - store-net
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
  stores-postgres:
    image: postgres:latest
    container_name: store_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5431:5432'
    volumes:
      - database_postgis:/var/lib/postgresql/data
    networks:
      - store-net

volumes:
  database_postgis:

networks:
  store-net:
    driver: bridge